version: "3"

services:
  raspi-remote-control-server:
    #build: .
    image: alicey/raspi-raspi-remote-control-server:latest
    container_name: raspi-remote-control-server
    environment:
      - REC_PORT=22
      - SEND_PORT=23
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "./app/:/opt/app"
    ports:
      - 32121:80