version: "3"

services:
  raspi-remote-control-server:
    #build: .
    image: alicey/raspi-raspi-remote-control-server:latest
    container_name: raspi-remote-control-server
    volumes:
        - "./app/:/opt/app"
    ports:
      - 32121:80